// <auto-generated />
using System;
using DotnetNTierArchitecture.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetNTierArchitecture.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231218192531_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotnetNTierArchitecture.Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(536),
                            TeamName = "Development"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(546),
                            TeamName = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(547),
                            TeamName = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(547),
                            TeamName = "HR"
                        });
                });

            modelBuilder.Entity("DotnetNTierArchitecture.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(798),
                            Email = "ayseyildiz@gmail.com",
                            Password = "123456",
                            TeamId = 1,
                            UserName = "ayseyildiz"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(800),
                            Email = "aliyilmaz@gmail.com",
                            Password = "112233",
                            TeamId = 2,
                            UserName = "aliyilmaz"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(801),
                            Email = "elifdemir@gmail.com",
                            Password = "123123",
                            TeamId = 3,
                            UserName = "elifdemir"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 18, 22, 25, 30, 776, DateTimeKind.Local).AddTicks(802),
                            Email = "ahmetkaya@gmail.com",
                            Password = "456789",
                            TeamId = 4,
                            UserName = "ahmetkaya"
                        });
                });

            modelBuilder.Entity("DotnetNTierArchitecture.Core.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ayşe",
                            LastName = "Yıldız",
                            NickName = "ayse",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ali",
                            LastName = "Yılmaz",
                            NickName = "ali",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Elif",
                            LastName = "Demir",
                            NickName = "elif",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ahmet",
                            LastName = "Kaya",
                            NickName = "ahmet",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("DotnetNTierArchitecture.Core.Models.User", b =>
                {
                    b.HasOne("DotnetNTierArchitecture.Core.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DotnetNTierArchitecture.Core.Models.UserProfile", b =>
                {
                    b.HasOne("DotnetNTierArchitecture.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotnetNTierArchitecture.Core.Models.Team", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
